### ISSUE TITLE
zef always fails on Windows 10 when trying to install a module

### ISSUE THREAD

**Issue by hjxkyw** [ugexe/zef#242] opened 2018-04-24 17:33 UTC
Can't install any module in WIndows 10.

Zef always fails with error:
No such method 'IO' for invocant of type 'Any'                     
  in method extract at C:\rakudo\share\perl6\site\sources\FDAE1C649
line 27                                                            
  in code  at C:\rakudo\share\perl6\site\sources\9062A39D0256C0BD79
  in method extract at C:\rakudo\share\perl6\site\sources\9062A39D0
ine 244                                                            
  in method fetch at C:\rakudo\share\perl6\site\sources\9062A39D025
e 183                                                              
  in sub MAIN at C:\rakudo\share\perl6\site\sources\9E04C517E18C976
  in block <unit> at C:\rakudo\share\perl6\site\resources\3DCC2E58B
  in sub MAIN at C:\rakudo\share\perl6\site\bin\zef line 2         
  in block <unit> at C:\rakudo\share\perl6\site\bin\zef line 2     

* perl6 -v
This is Rakudo Star version 2018.01 built on MoarVM version 2018.01
implementing Perl 6.c.

* zef list --installed
===> Found via C:\rakudo\share\perl6\site                                            
DBIish:ver<0.5.14>                                                                   
DateTime::Format                                                                     
DateTime::Parse:ver<0.0.1>                                                           
Debugger::UI::CommandLine                                                            
Digest::MD5:ver<0.05>:auth<Cosimo Streppone>                                         
Encode:ver<0.0.2>:auth<github:sergot>                                                
File::Directory::Tree:auth<labster>                                                  
File::Find:ver<0.1>                                                                  
File::Temp:ver<0.0.6>                                                                
File::Which:ver<1.0.0>                                                               
Grammar::Debugger:ver<1.0.1>:auth<github:jnthn>                                      
Grammar::Profiler::Simple:ver<0.02>                                                  
HTTP::Easy:ver<1.1.0>                                                                
HTTP::Status                                                                         
HTTP::UserAgent:ver<1.1.37>:auth<github:sergot>                                      
IO::Capture::Simple                                                                  
IO::String:ver<0.1.1>:auth<Rob Hoelz>                                                
JSON::Class:ver<0.0.10>:auth<github:jonathanstowe>                                   
JSON::Fast:ver<0.9.9>                                                                
JSON::Marshal:ver<0.0.14>:auth<github:jonathanstowe>                                 
JSON::Name:ver<0.0.2>:auth<github:jonathanstowe>                                     
JSON::RPC:ver<0.17.3>:auth<bbkr>                                                     
JSON::Tiny:ver<1.0>                                                                  
JSON::Unmarshal:ver<0.08>                                                            
LWP::Simple:ver<0.096>:auth<Cosimo Streppone>                                        
LibraryMake:ver<1.0.0>:auth<github:retupmoca>                                        
Linenoise:ver<0.1.1>:auth<Rob Hoelz>                                                 
META6:ver<0.0.19>:auth<github:jonathanstowe>                                         
MIME::Base64:ver<1.2.1>:auth<github:retupmoca>                                       
NativeHelpers::Blob:ver<0.1.10>:auth<github:salortiz>                                
OO::Monitors:ver<1.1>                                                                
PSGI:ver<1.2.0>                                                                      
Pod::To::BigPage:ver<0.2.1>:auth<Wenzel P. P. Peppmeyer>                             
Pod::To::HTML:ver<0.3.13>                                                            
SVG                                                                                  
SVG::Plot                                                                            
Shell::Command                                                                       
TAP::Harness:ver<0.0.3>:auth<Leon Timmermans>                                        
Template::Mojo:ver<0.1>                                                              
Template::Mustache:ver<1.0.1>:auth<github:softmoth>                                  
Terminal::ANSIColor:ver<0.4>                                                         
Test::META:ver<0.0.13>:auth<github:jonathanstowe>                                    
Test::Mock:ver<1.4>                                                                  
Test::Util::ServerPort:ver<0.0.1>:auth<github:jonathanstowe>                         
Test::When:ver<1.001008>                                                             
URI:ver<0.1.4>                                                                       
XML::Writer                                                                          
p6doc:ver<1.001002>                                                                  
zef:ver<0.2.0>:auth<github:ugexe>                                                    
===> Found via C:\rakudo\share\perl6                                                 
CORE:ver<6.c>:auth<perl>

**Comment by hjxkyw** [comment] 2018-04-24 18:36
Hi, thanks for your quick response.
I updated zef as per your instructions, but the issue remains.

Below is the output, now with complete lines (I hope).

> zef install HTTP::Server::Simple
===> Searching for: HTTP::Server::Simple
===> Updated cpan mirror:
https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan.json
===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects.json
No such method 'IO' for invocant of type 'Any'
  in method extract at
C:\rakudo\share\perl6\site\sources\890F9D00A774AD57DC9264CEFF37B0168D99AECB
(Zef::Extract) line 27
  in code  at
C:\rakudo\share\perl6\site\sources\533E866AF998B2C819CFEA6F1B1FA6AF32A420B6
(Zef::Client) line 271
  in method extract at
C:\rakudo\share\perl6\site\sources\533E866AF998B2C819CFEA6F1B1FA6AF32A420B6
(Zef::Client) line 246
  in method fetch at
C:\rakudo\share\perl6\site\sources\533E866AF998B2C819CFEA6F1B1FA6AF32A420B6
(Zef::Client) line 188
  in sub MAIN at
C:\rakudo\share\perl6\site\sources\199366F98A8098524D59A9916225C9836501889D
(Zef::CLI) line 149
  in block <unit> at
C:\rakudo\share\perl6\site\resources\D3E2C125FDB406C25F3B199F52E4361B9F20C563
line 3
  in sub MAIN at C:\rakudo\share\perl6\site\bin\zef line 2
  in block <unit> at C:\rakudo\share\perl6\site\bin\zef line 2


> perl6 -v
This is Rakudo Star version 2018.01 built on MoarVM version 2018.01
implementing Perl 6.c.

> zef list --installed
===> Found via C:\rakudo\share\perl6\site
DBIish:ver<0.5.14>
DateTime::Format
DateTime::Parse:ver<0.0.1>
Debugger::UI::CommandLine
Digest::MD5:ver<0.05>:auth<Cosimo Streppone>
Encode:ver<0.0.2>:auth<github:sergot>
File::Directory::Tree:auth<labster>
File::Find:ver<0.1>
File::Temp:ver<0.0.6>
File::Which:ver<1.0.0>
Grammar::Debugger:ver<1.0.1>:auth<github:jnthn>
Grammar::Profiler::Simple:ver<0.02>
HTTP::Easy:ver<1.1.0>
HTTP::Status
HTTP::UserAgent:ver<1.1.37>:auth<github:sergot>
IO::Capture::Simple
IO::String:ver<0.1.1>:auth<Rob Hoelz>
JSON::Class:ver<0.0.10>:auth<github:jonathanstowe>
JSON::Fast:ver<0.9.9>
JSON::Marshal:ver<0.0.14>:auth<github:jonathanstowe>
JSON::Name:ver<0.0.2>:auth<github:jonathanstowe>
JSON::RPC:ver<0.17.3>:auth<bbkr>
JSON::Tiny:ver<1.0>
JSON::Unmarshal:ver<0.08>
LWP::Simple:ver<0.096>:auth<Cosimo Streppone>
LibraryMake:ver<1.0.0>:auth<github:retupmoca>
Linenoise:ver<0.1.1>:auth<Rob Hoelz>
META6:ver<0.0.19>:auth<github:jonathanstowe>
MIME::Base64:ver<1.2.1>:auth<github:retupmoca>
NativeHelpers::Blob:ver<0.1.10>:auth<github:salortiz>
OO::Monitors:ver<1.1>
PSGI:ver<1.2.0>
Pod::To::BigPage:ver<0.2.1>:auth<Wenzel P. P. Peppmeyer>
Pod::To::HTML:ver<0.3.13>
SVG
SVG::Plot
Shell::Command
TAP::Harness:ver<0.0.3>:auth<Leon Timmermans>
Template::Mojo:ver<0.1>
Template::Mustache:ver<1.0.1>:auth<github:softmoth>
Terminal::ANSIColor:ver<0.4>
Test::META:ver<0.0.13>:auth<github:jonathanstowe>
Test::Mock:ver<1.4>
Test::Util::ServerPort:ver<0.0.1>:auth<github:jonathanstowe>
Test::When:ver<1.001008>
URI:ver<0.1.4>
XML::Writer
p6doc:ver<1.001002>
zef:ver<0.2.8>:auth<github:ugexe>
===> Found via C:\rakudo\share\perl6
CORE:ver<6.c>:auth<perl>


2018-04-24 15:18 GMT-03:00 Nick Logan <notifications@github.com>:

**Comment by ugexe** [comment] 2018-04-24 18:47
Thanks for the additional info. Could you do that one more time, but using the following commands to give me *even more* system specific information about what is going on? I should have included these in my previous instructions, so for that I apologize.

1) `SET ZEF_PLUGIN_DEBUG=1`
2) `zef install HTTP::Server::Simple --debug`
3) `SET ZEF_PLUGIN_DEBUG=0`

**Comment by hjxkyw** [comment] 2018-04-24 18:58
Jose Santana@TEC-JOSESANTANA C:\tmp\perl6
> SET ZEF_PLUGIN_DEBUG=1

Jose Santana@TEC-JOSESANTANA C:\tmp\perl6
> ef install HTTP::Server::Simple --debug
'ef' is not recognized as an internal or external command,
operable program or batch file.

Jose Santana@TEC-JOSESANTANA C:\tmp\perl6
> zef install HTTP::Server::Simple --debug
===> Searching for: HTTP::Server::Simple
[Plugin - cached] Checking: Zef::Repository::LocalCache
[Plugin - cached]       (OK) Plugin loaded successful
[Plugin - cached] (OK) Plugin is now usable: Zef::Repository::LocalCache
[Plugin - cpan] Checking: Zef::Repository::Ecosystems
[Plugin - cpan]         (OK) Plugin loaded successful
[Plugin - cpan] (OK) Plugin is now usable: Zef::Repository::Ecosystems
[Plugin - p6c] Checking: Zef::Repository::Ecosystems
[Plugin - p6c]  (OK) Plugin loaded successful
[Plugin - p6c] (OK) Plugin is now usable: Zef::Repository::Ecosystems
[Plugin - metacpan] Checking: Zef::Repository::MetaCPAN
[Plugin - metacpan]     (SKIP) Not enabled
===> Found: HTTP::Server::Simple:ver<0.1.2> [via
Zef::Repository::Ecosystems<p6c>]
===> Dependencies: Test::META
===> Fetching: HTTP::Server::Simple
[Plugin - git] Checking: Zef::Service::Shell::git
[Plugin - git]  (OK) Plugin loaded successful
[Plugin - git]  (OK) Probing successful
[Plugin - git] (OK) Plugin is now usable: Zef::Service::Shell::git
[Plugin - path] Checking: Zef::Service::FetchPath
[Plugin - path]         (OK) Plugin loaded successful
[Plugin - path]         (OK) Probing successful
[Plugin - path] (OK) Plugin is now usable: Zef::Service::FetchPath
[Plugin - curl] Checking: Zef::Service::Shell::curl
[Plugin - curl]         (OK) Plugin loaded successful
[Plugin - curl]         (OK) Probing successful
[Plugin - curl] (OK) Plugin is now usable: Zef::Service::Shell::curl
[Plugin - wget] Checking: Zef::Service::Shell::wget
[Plugin - wget]         (OK) Plugin loaded successful
[Plugin - wget]         (OK) Probing successful
[Plugin - wget] (OK) Plugin is now usable: Zef::Service::Shell::wget
[Plugin - pswebrequest] Checking: Zef::Service::Shell::PowerShell::download
[Plugin - pswebrequest]         (OK) Plugin loaded successful
[Plugin - pswebrequest]         (OK) Probing successful
[Plugin - pswebrequest] (OK) Plugin is now usable:
Zef::Service::Shell::PowerShell::download
Fetching with plugin: Zef::Service::Shell::git+{<anon|189690416>}
===> Fetching [OK]: HTTP::Server::Simple:ver<0.1.2> to C:\Users\Jose
Santana/.zef/tmp\1524596237.14840.8411\http-server-simple.git
===> Extracting: HTTP::Server::Simple
[Plugin - git] Checking: Zef::Service::Shell::git
[Plugin - git]  (OK) Plugin loaded successful
[Plugin - git]  (OK) Probing successful
[Plugin - git] (OK) Plugin is now usable: Zef::Service::Shell::git
[Plugin - path] Checking: Zef::Service::FetchPath
[Plugin - path]         (OK) Plugin loaded successful
[Plugin - path]         (OK) Probing successful
[Plugin - path] (OK) Plugin is now usable: Zef::Service::FetchPath
[Plugin - tar] Checking: Zef::Service::Shell::tar
[Plugin - tar]  (OK) Plugin loaded successful
[Plugin - tar]  (OK) Probing successful
[Plugin - tar] (OK) Plugin is now usable: Zef::Service::Shell::tar
[Plugin - p5tar] Checking: Zef::Service::Shell::p5tar
[Plugin - p5tar]        (OK) Plugin loaded successful
[Plugin - p5tar]        (OK) Probing successful
[Plugin - p5tar] (OK) Plugin is now usable: Zef::Service::Shell::p5tar
[Plugin - unzip] Checking: Zef::Service::Shell::unzip
[Plugin - unzip]        (OK) Plugin loaded successful
[Plugin - unzip]        (OK) Probing successful
[Plugin - unzip] (OK) Plugin is now usable: Zef::Service::Shell::unzip
[Plugin - psunzip] Checking: Zef::Service::Shell::PowerShell::unzip
[Plugin - psunzip]      (OK) Plugin loaded successful
[Plugin - psunzip]      (OK) Probing successful
[Plugin - psunzip] (OK) Plugin is now usable:
Zef::Service::Shell::PowerShell::unzip
Extracting with plugin: Zef::Service::Shell::git+{<anon|189690416>}
No such method 'IO' for invocant of type 'Any'
  in method extract at
C:\rakudo\share\perl6\site\sources\890F9D00A774AD57DC9264CEFF37B0168D99AECB
(Zef::Extract) line 27
  in code  at
C:\rakudo\share\perl6\site\sources\533E866AF998B2C819CFEA6F1B1FA6AF32A420B6
(Zef::Client) line 271
  in method extract at
C:\rakudo\share\perl6\site\sources\533E866AF998B2C819CFEA6F1B1FA6AF32A420B6
(Zef::Client) line 246
  in method fetch at
C:\rakudo\share\perl6\site\sources\533E866AF998B2C819CFEA6F1B1FA6AF32A420B6
(Zef::Client) line 188
  in sub MAIN at
C:\rakudo\share\perl6\site\sources\199366F98A8098524D59A9916225C9836501889D
(Zef::CLI) line 149
  in block <unit> at
C:\rakudo\share\perl6\site\resources\D3E2C125FDB406C25F3B199F52E4361B9F20C563
line 3
  in sub MAIN at C:\rakudo\share\perl6\site\bin\zef line 2
  in block <unit> at C:\rakudo\share\perl6\site\bin\zef line 2


Jose Santana@TEC-JOSESANTANA C:\tmp\perl6
>

2018-04-24 15:49 GMT-03:00 Nick Logan <notifications@github.com>:

**Comment by ugexe** [comment] 2018-04-24 19:14
Ah, I believe this is a duplicate of https://github.com/ugexe/zef/issues/204 "zef install fails when the path to .zef contains a space". i.e. your home directory contains a space (`C:\Users\Jose Santana\.zef`).

I suppose it is past time I took another serious look at this issue.

**Comment by ugexe** [comment] 2018-04-24 19:30
There is. Look at https://github.com/ugexe/zef/blob/50ebcaf54aa58064e0c5274248a070ddf5a2d450/resources/config.json#L3-L5

You would want to hardcode these to something like `C:\rakudo\.zef`, `C:\rakudo\.zef\store`, `C:\rakudo\.zef\tmp` instead of using `$*HOME`.

You should be able to do this without reinstalling zef. do `zef --help` and towards the end you will see:
```
CONFIGURATION /Users/ugexe/.rakudobrew/moar-blead-master/install/share/perl6/site/resources/BA7713C3085257BD4FC5F0F50B8A3DD977C9D894.json
    Enable or disable plugins that match the configuration that has field `short-name` that matches <short-name>

    --<short-name>  # `--cpan`  Enable plugin with short-name `cpan`
    --/<short-name> # `--/cpan` Disable plugin with short-name `cpan`
```
Modify the file to the right of `CONFIGURATION` to use these new values.

**Comment by hjxkyw** [comment] 2018-04-24 19:31
Thanks, I'll look into it later.

2018-04-24 16:30 GMT-03:00 Nick Logan <notifications@github.com>:

**Comment by hjxkyw** [comment] 2018-04-24 22:56
Hi

I did as you suggested above, and it worked.
Thanks.

**Comment by ugexe** [comment] 2018-04-25 02:10
Closing as a duplicate of #204 -- but note that I just resolve that issue with zef version 0.2.9 ( and hence this issue should be resolved in that version as well ).

**Closed by ugexe** 2018-04-25 02:10 UTC
