### ISSUE TITLE
WARNING: unhandled Failure detected in DESTROY:

### ISSUE THREAD

**Issue by Odud** [ugexe/zef#89] opened 2016-05-10 16:55 UTC
Try to install a module using Zef and go this warning (which occurred many times) before the final failure shown

I'm using Rakudo Star 2016.04 on Windows 10 and this was running as a non-admin user

C:\Users\langb>zef install IO::Socket::SSL
WARNING: unhandled Failure detected in DESTROY:
No such symbol 'Rakudo::Internals::JSON'
  in sub from-json at C:\rakudo\share\perl6\site\sources\9FA0AC28824EE9E5A9C0F99951CA870148AE378E (Zef) line 8
  in block  at sources\1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 554
  in code  at sources\1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 553
  in method is-installed at sources\1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 585
  in sub MAIN at C:\rakudo\share\perl6\site\sources\A9948E7371E0EB9AFDF1EEEB07B52A1B75537C31 (Zef::CLI) line 120
  in block <unit> at C:\rakudo\share\perl6\site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E line 1

and finally

Failure fetching to: False
  in code  at sources\1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 170
  in method fetch at sources\1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 139
  in sub MAIN at C:\rakudo\share\perl6\site\sources\A9948E7371E0EB9AFDF1EEEB07B52A1B75537C31 (Zef::CLI) line 147
  in block <unit> at C:\rakudo\share\perl6\site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E line 1

I'm guessing it's a zef problem and not something wrong with the module

**Comment by ugexe** [comment] 2016-05-10 19:47
There seems to be something off with the way rakudo handles this specific exception. I did not notice this failure earlier due to the fact I ran a golfed piece of code, which apparently never ran long enough to have `DESTROY` called. The fact it never happens on Linux makes it seem like a rakudo bug, but a workaround has been implemented.

Fixed in 4b7e052

Note: You will need to uninstall zef and then reinstall it. The best way to uninstall is to `cd` to the zef source code directory you would use to install from, and doing `perl6 -Ilib bin/zef -v uninstall zef`. Note not to use `zef uninstall zef` because on Windows it won't be able to delete the zef files while zef is running (running it from the cloned directory uses different file locations). This is the same reason you can't `--force` install zef if zef is already installed on Windows (rakudo related bug).

Thanks for the report @Odud !

**Comment by Odud** [comment] 2016-05-10 20:02
Thanks for this - I reinstalled zef, and the warnings have gone away. But I'm still getting a failure as below

C:\Users\langb>zef install IO::Socket::SSL
===> Searching for: IO::Socket::SSL
===> Searching for missing dependencies: OpenSSL
===> Fetching: IO::Socket::SSL
Failure fetching to: False
  in code  at sources\1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 170
  in method fetch at sources\1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 139
  in sub MAIN at C:\rakudo\share\perl6\site\sources\A9948E7371E0EB9AFDF1EEEB07B52A1B75537C31 (Zef::CLI) line 147
  in block <unit> at C:\rakudo\share\perl6\site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E line 1

**Comment by ugexe** [comment] 2016-05-10 20:08
Interesting... can you post the output from the following?
(first: `set ZEF_PLUGIN_DEBUG=1`)
`zef --debug install IO::Socket::SSL`

**Comment by ugexe** [comment] 2016-05-10 23:57
I believe I know what the problem is. Zef can fetch without requiring `git`. This can be seen when zef fetches the project listing for p6c for the first time as it will fall back to a non-git mirror. The problem is that the package list for p6c is exclusively `git` based urls, as each project does not supply a .zip mirror.

I am testing a branch, `git2zip`, which may be able to allow a totally `git`-less experience and should solve this issue.

**Comment by Odud** [comment] 2016-05-11 06:07
Hi Nick,

I did a quick test running as administrator this morning and it worked
fine, so maybe it is some kind of permissions issue? I will run with the
debug option later and send the output.

*Pete Barlow*

**Comment by Odud** [comment] 2016-05-11 06:30
Here's the output you requested. I ran zef uninstall IO::Socket::SSL as
administrator previous to this

C:\Users\langb>zef --debug install IO::Socket::SSL
===> Searching for: IO::Socket::SSL
[Plugin - cached] Checking: Zef::ContentStorage::LocalCache
[Plugin - cached]       (OK) Plugin loaded successful
[Plugin - cached] (OK) Plugin is now usable: Zef::ContentStorage::LocalCache
[Plugin - p6c] Checking: Zef::ContentStorage::P6C
[Plugin - p6c]  (OK) Plugin loaded successful
[Plugin - p6c] (OK) Plugin is now usable: Zef::ContentStorage::P6C
[Plugin - cpan] Checking: Zef::ContentStorage::CPAN
[Plugin - cpan]         (SKIP) Not enabled
===> Found: IO::Socket::SSL:auth('github:sergot')
===> Dependencies: OpenSSL
===> Fetching: IO::Socket::SSL
[Plugin - git] Checking: Zef::Shell::git
[Plugin - git]  (OK) Plugin loaded successful
[Plugin - git]  (OK) Probing successful
[Plugin - git] (OK) Plugin is now usable: Zef::Shell::git
Fetching with plugin: Zef::Shell::git+{<anon|106869504>}
===> Fetched: IO::Socket::SSL to C:\Users\langb\.zef\tmp\io-socket-ssl.git
===> Extracting: IO::Socket::SSL
[Plugin - git] Checking: Zef::Shell::git
[Plugin - git]  (OK) Plugin loaded successful
[Plugin - git]  (OK) Probing successful
[Plugin - git] (OK) Plugin is now usable: Zef::Shell::git
Extracting with plugin: Zef::Shell::git+{<anon|106869504>}
===> Extracted: IO::Socket::SSL to
C:\Users\langb\.zef\store\io-socket-ssl.git\062724b66d7d7220e94d8da6321ba109fab911e5
===> Filtering: IO::Socket::SSL:auth('github:sergot')
===> Filtering [OK] for IO::Socket::SSL:auth('github:sergot')
===> # SKIP: No Build.pm for IO::Socket::SSL:auth('github:sergot')
===> Testing: IO::Socket::SSL:auth('github:sergot')
[Plugin - prove] Checking: Zef::Shell::prove
[Plugin - prove]        (OK) Plugin loaded successful
[Plugin - prove]        (OK) Probing successful
[Plugin - prove] (OK) Plugin is now usable: Zef::Shell::prove
Testing with plugin: Zef::Shell::prove+{<anon|106869504>}
t/01-basic.t ..
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 2/2 subtests

Test Summary Report
-------------------
t/01-basic.t (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 2 tests but ran 0.
Files=1, Tests=0, 51 wallclock secs ( 0.03 usr +  0.03 sys =  0.06 CPU)
Result: FAIL
Cannot locate native library
'C:\rakudo\share\perl6\site\resources\5AC8B407FC19FF40B94E90605A758D6AF872EF83.dll':
error 0x7f
  in method setup at sources\24DD121B5B4774C04A7084827BFAD92199756E03
(NativeCall) line 279
  in method CALL-ME at sources\24DD121B5B4774C04A7084827BFAD92199756E03
(NativeCall) line 290
  in method new at sources\6A1EAA8F4604152BF1E7B1F71E25F82D2C1FA912
(OpenSSL) line 33
  in method initialize at
C:\Users\langb\.zef\store\io-socket-ssl.git\062724b66d7d7220e94d8da6321ba109fab911e5\lib\IO\Socket\SSL.pm6
(IO::Socket::SSL) line 67
  in method new at
C:\Users\langb\.zef\store\io-socket-ssl.git\062724b66d7d7220e94d8da6321ba109fab911e5\lib\IO\Socket\SSL.pm6
(IO::Socket::SSL) line 58
  in block <unit> at t/01-basic.t line 7

===> Testing [FAIL]: IO::Socket::SSL:auth('github:sergot')
Aborting due to test failure: IO::Socket::SSL:auth('github:sergot') (use
--force to override)
  in code  at sources\1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA
(Zef::Client) line 285
  in method test at sources\1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA
(Zef::Client) line 264
  in code  at sources\1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA
(Zef::Client) line 433
  in method install at sources\1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA
(Zef::Client) line 430
  in sub MAIN at
C:\rakudo\share\perl6\site\sources\A9948E7371E0EB9AFDF1EEEB07B52A1B75537C31
(Zef::CLI) line 150
  in block <unit> at
C:\rakudo\share\perl6\site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E
line 1


C:\Users\langb>

*Pete Barlow*

**Comment by ugexe** [comment] 2016-05-11 17:21
Hey Pete, thanks for giving that a shot.

I'm actually more confused now than originally. Your original error (ignoring the warnings) was a problem with the `Fetch` phase. I had assumed the problem was you did not have `git` installed, but that does not seem to be the case considering it works fine for you with administrator privledges. We will call this problem A.

Now lets consider your last 2 comments. The first one says it installed `IO::Socket::SSL` as administrator, so we can assume the testing passed. After this you ran `zef uninstall IO::Socket::SSL`, then attempt to reinstall it but it fails in testing. The interesting part of this is that in the error message it shows the location the openssl dll files would be *if they were installed* `C:\rakudo\share\perl6\site\resources\<sha1>.dll`. But clearly they are not installed or there would be no error. The fact rakudo shows that path, complete with the `<sha1>.dll` instead of `ssleay.dll`, means that path string (not the actual path, just a string used to map `ssleay.dll` name to `<sha1>.dll` location) is still around somewhere. We will call this problem B.

Problem A could be caused by a few things, permissions being one of them. At one time I encountered a situation where, on Windows, `git` was able to clone `git://` scheme uris but *not* `https://` uris. Its possible that your previous run as administrator worked for `https`, which copies over to `$*HOME/.zef/tmp/io-socket-ssl.git` (even eventually to `$*HOME/.zef/store/io-socket-ssl.git/<sha1>/`). Its then possible that your next run after the uninstall was able to succeed due to the folder having been created from the previous run. Unfortunately to test this theory requires the following steps:

    1. Delete C:\Users\langb\.zef
    2. Delete C:\rakudo\share\perl6\site (this effectively uninstalls all modules)
    3. Delete C:\Users\langb\.perl6
    4. cd to wherever you have `zef` cloned to and reinstall it
    5. Reinstall IO::Socket::SSL without administer privledges
    6. Step #5 should fail, but what we need to know is if `C:\Users\langb\tmp\io-socket-ssl.git\` exists and if it contains files. We can be pretty sure it won't exist.
    7. Repeat steps 1-3
    8. cd to wherever you have `zef` cloned, and edit `resources/config.json` such that:

        {
            "short-name" : "git",
            "module" : "Zef::Shell::git",
            "options" : {
                "scheme" : "https"
            }
        },

    is changed exactly (including a removed trailing comma) to:

        {
            "short-name" : "git",
            "module" : "Zef::Shell::git"
        },

    9. Reinstall `zef`
    10. Reinstall IO::Socket::SSL without administer privledges.
    11. Check if `C:\Users\langb\tmp\io-socket-ssl.git\` exists

This tests 2 different theories: The first is that `mkdir` is not able to create the directory before attempting to `git clone`. The second is that `git clone` works with `git://` protocol but not `https://` protocol for some reason. If the above is too much for you (and I would not blame you if you think it is) you could test the second theory with:

    `git clone git://github.com/sergot/io-socket-ssl.git C:\Users\langb\test-dir-1\tmp`
    `git clone https://github.com/sergot/io-socket-ssl.git C:\Users\langb\test-dir-2\tmp`

If both of these work then I can probably assume its related to `mkdir` not creating the path first. If the first one works but the second one does not then the fix is simply editing the `config.json` to use `"scheme" : "git"` instead of `"scheme": "https"`. If both work then there is a good chance it is also related to `mkdir` not creating the path first, but for a different reason.

Now to examine problem B. I don't think this is `zef`, but rakudo and precompilation related. As mentioned earlier the error says it cannot find a dll thats located in the installation location. So we know the file was delete, but how does rakudo know to look for it there? My guess is these paths are contained in the precompiled files from when it was installed earlier, and rakudo fails to invalidate these as it should. You can test this theory by deleting:

    1. C:\Users\langb\.perl6
    2. C:\rakudo\share\perl6\site\precomp
    3. C:\Users\langb\.zef\store\io-socket-ssl.git\<single sha1 folder>\lib\.precomp

I would delete 1 and 2, then see if you get the same error. If you do then redelete 1 and 2 (if they get created again) and also 3, then retest. If deleting 3 solves the issue then the solution can be integrated into zef. If deleting 1 and 2 solves the issue its a rakudo bug.


Hopefully this wall of text did not scare you off! Don't feel obligated to test any of this, but if you do test any of these it would help. This is mostly a reference for myself so I can attempt to recreate the issues and store possible solutions before I forget. The odd thing is I develop on Windows 10 and am able to install IO::Socket::SSL without administer privledges. The only difference I can tell so far is I install rakudo from source instead of using Rakudo Star, so i'm going to give that a shot and see what happens.

**Comment by ugexe** [comment] 2016-05-11 19:12
The good news is I know how you can get this to work.

For some reason installing `IO::Socket::SSL` will fail with the same error you posted if `OpenSSL` is already installed. I'm not exactly sure what this means yet other than its not a `zef` error. If you `zef uninstall IO::Socket::SSL` `zef uninstall OpenSSL`,  doing `zef install IO::Socket::SSL` should work for you. `OpenSSL` still gets installed as a dependency; The problem has something to do with linking against the already installed dll files, but i'm not sure what. Maybe its because of how rakudo renames them?

The earlier problem with `Fetch` is probably a permissions or git problem. One possibility is a run-time call to rakudos `mkdir` sets the permissions incorrect. Another is the `git clone` itself results in incorrect permissions. This is corroborated by your initial success with running as administrator, which may have allowed the neccesary directories to be created in `$*HOME/.zef` or `<rakudo dir>/share/site`. Those directories would have been left even after uninstalling, so later when you ran as non-administrator the directories were already available.

**Comment by Odud** [comment] 2016-05-12 18:19
Thanks Nick,

I will try things tonight. I realised that there may have been some files
relating to IO::Socket:SSL lying around as I had failures installing that
with Panda (this was an issue with that module which has now been fixed).
So I think I will pick something that I know I haven't tried to install
before as it might make things clearer.

**Comment by ugexe** [comment] 2016-05-12 18:23
I've updated `OpenSSL` to fix the `cannot locate native library` errors. Now you can install `OpenSSL` followed by `IO::Socket::SSL`, or uninstall+reinstall `IO::Socket::SSL`

**Comment by Odud** [comment] 2016-05-12 21:18
Hi Nick,

I'm now very confused, everything seemed to work (see below). But there is
no sign of the modules in C:\rakudo\share\perl6\site or any of its
sub-directories. I also tried the above running as admin, same result. Am I
correct in assuming this where the installs should go?

*C:\Users\langb>zef --verbose install IO::Socket::SSL*
===> Searching for: IO::Socket::SSL
===> Found: IO::Socket::SSL:auth('github:sergot')
===> Searching for missing dependencies: OpenSSL
===> Found dependencies: OpenSSL:ver('0.1.0'):auth('github:sergot')
===> Fetching: OpenSSL
===> Fetched: OpenSSL to C:\Users\langb\.zef\tmp\openssl.git
===> Testing: OpenSSL:ver('0.1.2'):auth('github:sergot')
t/01-basic.t ........... ok
t/02-socket.t .......... ok
t/03-rsa.t ............. ok
t/04-crypt.t ........... ok
t/10-client-ca-file.t .. ok
All tests successful.
Files=5, Tests=34, 106 wallclock secs ( 0.08 usr +  0.03 sys =  0.11 CPU)
Result: PASS
# Got a redirect, following...
===> Testing [OK] for OpenSSL:ver('0.1.2'):auth('github:sergot')
===> Testing: IO::Socket::SSL:auth('github:sergot')
t/01-basic.t .. ok
All tests successful.
Files=1, Tests=2, 49 wallclock secs ( 0.05 usr +  0.03 sys =  0.08 CPU)
Result: PASS
===> Testing [OK] for IO::Socket::SSL:auth('github:sergot')
===> Installing: OpenSSL:ver('0.1.2'):auth('github:sergot')
===> Install [OK] for OpenSSL:ver('0.1.2'):auth('github:sergot')
===> Installing: IO::Socket::SSL:auth('github:sergot')
===> Install [OK] for IO::Socket::SSL:auth('github:sergot')

*C:\Users\langb>zef --installed list*
*===> Found via C:\rakudo\share\perl6\site*
OpenSSL:ver('0.1.2'):auth('github:sergot')
Template::Mustache:auth('github:softmoth')
SVG::Plot
Terminal::ANSIColor
URI:ver('0.1.1')
DBIish
JSON::Fast:ver('0.3')
File::Temp
Encode:ver('0.0.2'):auth('github:sergot')
NativeHelpers::Blob:ver('0.1.8'):auth('github:salortiz')
HTML::Restrict:ver('0.1')
Linenoise:ver('0.1.0'):auth('Rob Hoelz')
Grammar::Debugger
HTML::Parser::XML:ver('0.1.0'):auth('github:tony-o')
panda:ver('0.1')
Shell::Command
panda:ver('2016.02')
DBIish:ver('0.5.6')
p6doc
JSON::Fast:ver('0.4')
Data::Dump:ver('0.0.1')
HTTP::UserAgent:ver('1.1.16'):auth('github:sergot')
Find::Bundled:ver('1.0.0'):auth('github:retupmoca')
XML
File::Find:ver('0.1')
LWP::Simple:ver('0.086'):auth('Cosimo Streppone')
JSON::RPC:ver('0.17.1'):auth('Pawel Pabian')
LibraryMake:ver('1.0.0'):auth('github:retupmoca')
zef:auth('github:ugexe')
File::Temp
Debugger::UI::CommandLine
MIME::Base64:ver('1.2'):auth('github:retupmoca')
DateTime::Parse:ver('0.0.1')
Bailador
IO::Socket::SSL:auth('github:sergot')
Digest:ver('0.3.4'):auth('Lucien Grondin')
HTTP::Easy
Template::Mojo:ver('0.1')
PSGI
Grammar::Profiler::Simple:ver('0.01'):auth('Jonathan Scott Duff')
JSON::Tiny
SVG
Native::Resources:ver('0.1.0'):auth('Rob Hoelz')
File::Directory::Tree:auth('labster')
String::CRC32:ver('0.04'):auth('Cosimo Streppone')
HTTP::Status
IO::Capture::Simple
Test::Mock
Pod::To::HTML
Crypt::RC4:ver('0.0.2')
HTML::Entity:auth('Alexander Moquin')
*===> Found via C:\rakudo\share\perl6*
CORE:ver('6.c'):auth('perl')




*Pete Barlow*

**Comment by ugexe** [comment] 2016-05-12 21:28
They are there, but when a module gets installed it no longer retains its original layout or file names. Every file name gets turned into a `sha1` identity, and all such files are put into the same directory (Again, this is rakudo itself that does this). If you look in `share/perl6/site/dist` each file represents the meta data for a distribution. You can open these files and look at the `files` and `provides` sections to see what `sha1` filename the original file names are now mapped to.

`panda` might store its cache there under some directory, but those files are not used except for installing files into the format listed above. `zef` simply stores its cache in `$*HOME/.zef` by default but can be configured to use other locations (see `resources/config.json`)

**Comment by Odud** [comment] 2016-05-13 08:53
Nick,

Thanks for your explanation it all makes sense and I think that zef seems
to working fine now. What was confusing me was that I had a directory lib
under c:\rakudo\share\perl6\site and I was expecting to see the new modules
appearing in there - I think this was a hangover from when I first
installed 2015.09. Having done a clean install of 2016.04 that's no longer
there.

*Pete Barlow*

**Closed** 2016-05-19 03:54 UTC
