### ISSUE TITLE
Cannot unbox a type object (Mu) to int.

### ISSUE THREAD

**Issue by FCO** [ugexe/zef#406] opened 2021-07-20 18:29 UTC
I'm not sure that's happening because of zen, but I've gotten that trying to install 2 different modules (it's also possible it's something related to may machine and/or my installation). But I'm getting that error trying to instal Red and App::Mi6.

## Context

<img width="833" alt="image" src="https://user-images.githubusercontent.com/99834/126376441-3ccf6eca-995a-4e82-b938-b295c62c5a74.png">

<img width="798" alt="image" src="https://user-images.githubusercontent.com/99834/126376326-52509c66-3527-4410-b60d-3730bb96ada7.png">

## Steps to Reproduce
zef install Red
zef install App::Mi6

## Your Environment

* raku -v
Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2021.06-87-g50bd1717c.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2021.06-22-gfb5d26a7e.
* zef list --installed
===> Found via /Users/fernando/.rakubrew/versions/moar-master/install/share/perl6/core
CORE:ver<6.d>:auth<perl>
===> Found via /Users/fernando/.rakubrew/versions/moar-master/install/share/perl6/site
6pm:ver<0.0.11>
App::GPTrixie:ver<0.29>
App::Mi6:ver<0.3.1>:auth<cpan:SKAJI>
App::Mi6:ver<1.0.1>:auth<cpan:SKAJI>
Base64:ver<0.0.2>:auth<github:ugexe>
CPAN::Uploader::Tiny:ver<0.0.6>:auth<cpan:SKAJI>
Config::INI
Cro::Core:ver<0.8.3>
Cro::HTTP:ver<0.8.3>
Cro::TLS:ver<0.8.3>
Cro::WebApp:ver<0.8.3>
Cro::WebSocket:ver<0.8.3>
Crypt::AnyPasswordHash:ver<0.0.4>:auth<github:jonathanstowe>:api<1.0>
Crypt::Libcrypt:ver<0.1.0>:auth<github:jonathanstowe>:api<1.0>
Crypt::Random:ver<0.4.1>:auth<github:skinkade>
DB::Pg:ver<0.6>
DBIish:ver<0.6.0>
DBIish:ver<0.6.2>:auth<github:raku-community-modules>
DOM::Tiny:ver<0.5.2>:auth<github:zostay>
DateTime::Parse:ver<0.9.1>
Digest::HMAC:ver<1.0.2>:auth<github:retupmoca>
Digest::SHA1::Native:ver<0.04>
Digest::SHA256::Native:ver<0.03>
Digest:ver<0.3.4>:auth<Lucien Grondin>
Distribution::Builder::MakeFromJSON:ver<0.6>:auth<github:niner>
Docker::File:ver<1.0>:auth<github:jnthn>
Encode:ver<0.0.3>:auth<github:sergot>
File::Directory::Tree:auth<labster>
File::Find:ver<0.1>
File::Ignore:ver<1.1>:auth<Jonathan Worthington <jnthn@jnthn.net>>
File::Temp:ver<0.0.8>
File::Which:ver<1.0.1>
Grammar::Debugger:ver<1.0.1>:auth<github:jnthn>
HTML::Escape:ver<0.0.1>
HTTP::HPACK:ver<0.9.2>
HTTP::Roles:ver<0.2.0>:auth<github:tony-o>
HTTP::Server::Async:ver<0.1.9>:auth<github:tony-o>
HTTP::Status:ver<0.0.1>
HTTP::Tinyish:ver<0.1.4>:auth<cpan:SKAJI>
HTTP::UserAgent:ver<1.1.49>:auth<github:sergot>
IO::Path::ChildSecure:ver<1.001011>
IO::Socket::Async::SSL:ver<0.7.5>
IO::Socket::SSL:ver<0.0.1>:auth<github:sergot>
IRC::Client:ver<3.007011>
IRC::TextColor:ver<0.3.0>:auth<github:samcv>
Inline::Perl5:ver<0.50>:auth<github:niner>
JSON::Class:ver<0.0.14>:auth<github:jonathanstowe>:api<1.0>
JSON::Fast:ver<0.10>
JSON::JWT:ver<1.0>:auth<github:retupmoca>
JSON::Marshal:ver<0.0.18>:auth<github:jonathanstowe>:api<1.0>
JSON::Name:ver<0.0.4>:auth<github:jonathanstowe>:api<1.0>
JSON::Pretty:ver<0.1.0>:auth<github:FROGGS>
JSON::Tiny:ver<1.0>
JSON::Unmarshal:ver<0.08>
Keyring:ver<0.1.0>:auth<cpan:JMASLAK>
LibUUID:ver<0.5>:auth<github:CurtTilmes>
LibraryMake:ver<1.0.0>:auth<github:retupmoca>
License::SPDX:ver<3.9.0>:auth<github:jonathanstowe>:api<1.0>
Linenoise:ver<0.1.1>:auth<Rob Hoelz>
Lingua::Conjunction:ver<1.001001>
Log::Timeline:ver<0.3>
META6:ver<0.0.23>:auth<github:jonathanstowe>:api<1.0>
MIME::Base64:ver<1.2.1>:auth<github:retupmoca>
NativeHelpers::Blob:ver<0.1.12>:auth<github:salortiz>
NativeLibs:ver<0.0.7>:auth<github:salortiz>
Number::Denominate:ver<2.002001>
OO::Monitors:ver<1.1.1>
OpenSSL:ver<0.1.23>:auth<github:sergot>
Pastebin::Gist:ver<1.004002>
Pod::Load:ver<0.5.5>
Pod::To::HTML:ver<0.7.0>:auth<github:Raku>
Pod::To::Markdown:ver<v.0.1.4>
RedX::HashedPassword:ver<0.0.4>:auth<github:jonathanstowe>
SVG
SVG::Plot
Shell::Command
Stats:ver<0.0.6>:auth<github:MattOates>
System::Query:ver<0.1.4>:auth<github:tony-o>
TAP:ver<0.1.0>
Template::Mustache:ver<1.1.4>:auth<github:softmoth>
Term::Choose:ver<1.6.9>
Term::termios:auth<github:krunen>
Terminal::ANSIColor:ver<0.5>
Terminal::Getpass:ver<0.0.8>
Test::META:ver<0.0.16>:auth<github:jonathanstowe>:api<1.0>
Test::Mock:ver<1.5>
Test::Output:ver<1.001002>
Test::Util::ServerPort:ver<0.0.2>:auth<github:jonathanstowe>:api<1.0>
Test::When:ver<1.001008>
Text::Diff::Sift4:ver<1.4.1>
Text::Markdown:ver<1.1.0>:auth<github:retupmoca>
URI:ver<0.3.0>
UUID:ver<1.0.0>:auth<github:retupmoca>
WWW:ver<1.005004>:auth<github:perl6-community-modules>
Whateverable:ver<1.0.10>
XML::Writer
XML:ver<0.3.0>:auth<Timothy Totten>
YAMLish:ver<0.0.5>
ake:ver<0.0.3>:auth<Jonathan Scott Duff <duff@pobox.com>>
cro:ver<0.8.3>
if:ver<0.1.1>:auth<github:FROGGS>
payprop:ver<0.0.2>:auth<Fernando Correa de Oliveira>:api<1>
zef:ver<0.11.9>:auth<github:ugexe>:api<0>
zef:ver<0.8.4>:auth<github:ugexe>:api<0>

**Comment by raydiak** [comment] 2021-07-21 01:19
After some hunting, this only manifests on extremely bleading-edge rakudo, and is due to rakudo/rakudo#4471

**Comment by lizmat** [comment] 2021-07-21 08:58
Should be fixed with https://github.com/rakudo/rakudo/commit/efb3116a90a1c6a7eff73b141aec79d345be0c28

@raydiak Thanks for the spot and the golf.

**Comment by raydiak** [comment] 2021-07-21 09:38
I can confirm that this problem no longer manifests for me.

@lizmat Thanks for the speedy fix.

**Comment by FCO** [comment] 2021-07-21 10:33
thanks!

**Closed** 2021-07-21 10:46 UTC
