### ISSUE TITLE
Failed to resolve dependencies, but none are reported missing

### ISSUE THREAD

**Issue by Tyil** [ugexe/zef#224] opened 2018-01-04 10:50 UTC
When trying to `zef install --deps-only .`, `zef` bails out with the message `"Failed to find dependencies:"`, but there's no list of which dependencies it couldn't resolve.

## Context
I'm trying to install the deps for a module so I can test it. An example is available on [one of my travis builds](https://travis-ci.org/scriptkitties/perl6-app-assixt/builds/324871237#L1317).

I've been able to reproduce it locally as well. If I install one of the dependencies, `Dist::Helper`, manually using `zef install Dist::Helper` first, a later call to `zef install --deps-only .` works with no problems.

I've looked at some part of this myself, by throwing in some `dd` calls. It appears that `+@needed` return `12`, whereas `+@prereq-candidates` returns `11`. This makes the dependency resolution fail. However, in the output part, a new `@not-found` is made based on a `@needed.grep(...)` call. The `@not-found` list is empty, thus the output shows an empty list.

## Expected Behavior
Either install all dependencies, or provide a list of missing dependencies.

## Actual Behavior
Dependencies do not get installed, an error is shown that some dependencies are missing, but no list of the actual dependencies that could not be resolved.

## Steps to Reproduce
```
git clone https://github.com:scriptkitties/perl6-app-assixt.git
cd perl6-app-assixt
zef install --deps-only .
```

### perl6 -v
```
This is Rakudo version 2017.11 built on MoarVM version 2017.11
implementing Perl 6.c.
```

### zef list --installed
```
===> Found via /var/rakudobrew/moar-2017.11/install/share/perl6    
CORE:ver<6.c>:auth<perl>
===> Found via /var/rakudobrew/moar-2017.11/install/share/perl6/sit
zef:ver<0.1.32>:auth<github:ugexe>
```

**Comment by ugexe** [comment] 2018-01-04 15:29
Duplicate of https://github.com/ugexe/zef/issues/157

**Closed** 2018-01-13 06:49 UTC
